'use client';
import { useRef, useState } from 'react';
import {profile,projects} from './content';
export default function Home(){
 const [active,setActive]=useState(0); const rail=useRef<HTMLDivElement>(null);
 function go(i:number){const n=(i+projects.length)%projects.length;setActive(n);rail.current?.children[n]?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest',inline:'center'});}
 return <main><a className="skip" href="#work">跳到作品</a><header className="nav"><a href="/" className="logo" aria-label="Chenke Huang 首页">CH<span>®</span></a><span className="nav-note">独立思考，自由探索。</span><a className="nav-link" href="/about">关于我 <span>↗</span></a></header>
 <section className="hero"><div className="hero-top"><p>{profile.tagline}</p><span className="edition">PORTFOLIO<br/>DESIGN & EXPLORATION</span></div><h1 aria-label={profile.name}><span>{profile.firstName}</span><span className="surname">{profile.lastName}<i aria-hidden="true">↗</i></span></h1><div className="hero-bottom"><span>{profile.role}</span><a href="#work">探索作品 <span>↓</span></a><span className="status"><i/> 持续更新中</span></div></section>
 <section className="work" id="work"><div className="section-line"><h2>Selected work<span>精选作品</span></h2><span>01 — 03</span></div><div className="project-rail" ref={rail} onScroll={()=>{if(rail.current){const el=rail.current;setActive(Math.min(projects.length-1,Math.round(el.scrollLeft/(el.children[0].clientWidth+24))))}}}>{projects.map(p=><a className="project-card" href={'/work/'+p.slug} key={p.slug}><div className="project-art" style={{background:p.color}}>{p.image?<img src={p.image} alt={p.title+' 项目封面'}/>:<><span className="art-label">PROJECT / {p.number}</span><strong>{p.number}</strong><span className="art-caption">{p.category}<span>内容即将呈现</span></span><span className="view-mark">↗</span></>}</div><div className="project-info"><h3>{p.title}</h3><span>{p.category} ↗</span></div></a>)}</div><div className="rail-controls"><span>({String(active+1).padStart(2,'0')} / 03)</span><div><button onClick={()=>go(active-1)} aria-label="上一个项目">←</button><button onClick={()=>go(active+1)} aria-label="下一个项目">→</button></div></div></section>
 <footer className="home-footer"><span>CHENKE HUANG © {new Date().getFullYear()}</span><a href="/about">认识一下？ ↗</a><a href="#top" onClick={e=>{e.preventDefault();window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}}>回到顶部 ↑</a></footer></main>
}
