import {readFileSync,writeFileSync,mkdirSync,copyFileSync,cpSync} from 'node:fs';
const {profile,projects}=JSON.parse(readFileSync('app/content.json','utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=s=>/^\/(?!\/)[^\\]*$/.test(s)?s:'';
mkdirSync('out',{recursive:true});cpSync('public','out',{recursive:true});
writeFileSync('out/style.css',readFileSync('app/globals.css','utf8').replace(/^@import .*;\n/gm,''));
const head=title=>`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} — Chenke Huang</title><meta name="description" content="产品与交互设计作品集"><link rel="stylesheet" href="/style.css"></head><body>`;
const nav=(home=false)=>`<header class="nav"><a href="/" class="logo" aria-label="Chenke Huang 首页">CH<span>•</span></a><span class="nav-note">独立思考，自由探索。</span><a class="nav-link" href="${home?'/about/':'/#work'}">${home?'关于我':'返回作品'} ↗</a></header>`;
const foot=`<footer class="home-footer"><span>${esc(profile.name)} © ${new Date().getFullYear()}</span><a href="/about/">认识一下？ ↗</a><a href="#" data-top>回到顶部 ↑</a></footer>`;
const shell=(title,body)=>head(title)+body+'<script src="/interaction.js" defer></script></body></html>';
const card=p=>`<a class="project-card" href="/work/${esc(p.slug)}/"><div class="project-art" style="background:${esc(p.color)}">${url(p.image)?`<img src="${esc(p.image)}" alt="${esc(p.title)} 项目封面">`:`<span class="art-label">PROJECT / ${esc(p.number)}</span><strong>${esc(p.number)}</strong><span class="art-caption">${esc(p.category)}<span>内容即将呈现</span></span><span class="view-mark">↗</span>`}</div><div class="project-info"><h3>${esc(p.title)}</h3><span>${esc(p.category)} ↗</span></div></a>`;
writeFileSync('out/index.html',shell('作品集',`<main><a class="skip" href="#work">跳到作品</a>${nav(true)}<section class="hero"><div class="hero-top"><p>${esc(profile.tagline)}</p><span class="edition">PORTFOLIO<br>DESIGN & EXPLORATION</span></div><h1 aria-label="${esc(profile.name)}"><span>${esc(profile.firstName)}</span><span class="surname">${esc(profile.lastName)}<i aria-hidden="true">↗</i></span></h1><div class="hero-bottom"><span>${esc(profile.role)}</span><a href="#work">探索作品 <span>↓</span></a><span class="status"><i></i>持续更新中</span></div></section><section class="work" id="work"><div class="section-line"><h2>Selected work<span>精选作品</span></h2><span>01 — ${String(projects.length).padStart(2,'0')}</span></div><div class="project-rail">${projects.map(card).join('')}</div><div class="rail-controls"><span data-counter>(01 / ${String(projects.length).padStart(2,'0')})</span><div><button data-prev aria-label="上一个项目">←</button><button data-next aria-label="下一个项目">→</button></div></div></section>${foot}</main>`));
mkdirSync('out/about',{recursive:true});
writeFileSync('out/about/index.html',shell('关于我',nav()+`<main class="inside"><span class="edition">A LITTLE ABOUT ME</span><h1>你好，<br>我是 ${esc(profile.firstName)}。</h1><p class="inside-intro">${esc(profile.bio)}</p><div class="about-grid"><div><h2>设计方向</h2><p>${esc(profile.role)}</p></div><div><h2>联系</h2>${/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(profile.email)?`<a class="back-link" href="mailto:${esc(profile.email)}">${esc(profile.email)} ↗</a>`:'<p class="placeholder-label">联系方式即将更新。</p>'}</div></div></main>`+foot));
for(let i=0;i<projects.length;i++){const p=projects[i],next=projects[(i+1)%projects.length];if(!/^[a-z0-9-]+$/.test(p.slug))throw Error('Invalid project slug');mkdirSync('out/work/'+p.slug,{recursive:true});writeFileSync('out/work/'+p.slug+'/index.html',shell(p.title,nav()+`<main class="inside"><span class="edition">PROJECT / ${esc(p.number)}</span><h1>${esc(p.title)}</h1><p class="inside-intro">${esc(p.description)}</p><div class="detail-cover" style="background:${esc(p.color)}">${url(p.image)?`<img src="${esc(p.image)}" alt="${esc(p.title)} 项目封面">`:esc(p.number)}</div><div class="detail-meta"><div><small>设计类别</small>${esc(p.category)}</div><div><small>项目时间</small>${esc(p.year)}</div><div><small>状态</small>${esc(p.status)}</div></div>${p.sections.map((s,j)=>`<section class="detail-section"><h2>${String(j+1).padStart(2,'0')} / ${esc(s.title)}</h2><p>${esc(s.text)}</p></section>`).join('')}<a class="next-project" href="/work/${esc(next.slug)}/"><span>下一个：${esc(next.title)}</span><span>↗</span></a></main>`));}
writeFileSync('out/interaction.js',`const rail=document.querySelector('.project-rail');let active=0;const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;function update(){if(!rail)return;let best=Infinity;[...rail.children].forEach((el,i)=>{const d=Math.abs(el.offsetLeft-rail.offsetLeft-rail.scrollLeft);if(d<best){best=d;active=i}});if(rail.scrollLeft+rail.clientWidth>=rail.scrollWidth-2)active=rail.children.length-1;document.querySelector('[data-counter]').textContent='('+String(active+1).padStart(2,'0')+' / '+String(rail.children.length).padStart(2,'0')+')'}function go(delta){if(!rail)return;active=(active+delta+rail.children.length)%rail.children.length;const el=rail.children[active];rail.scrollTo({left:el.offsetLeft-rail.offsetLeft,behavior:reduced()?'instant':'smooth'})}document.querySelector('[data-prev]')?.addEventListener('click',()=>go(-1));document.querySelector('[data-next]')?.addEventListener('click',()=>go(1));rail?.addEventListener('scroll',update,{passive:true});document.querySelector('[data-top]')?.addEventListener('click',e=>{e.preventDefault();window.scrollTo({top:0,behavior:reduced()?'instant':'smooth'})});`);
console.log('Built 5 pages to out/');
